{% set name = "pyclipper" %}
{% set version = "1.1.0.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f1acd74bdb8c114fea2eab0bcf76460d1ef4b4120953e410fc7c638eb79e9e98

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools_scm_git_archive
    - setuptools_scm

  run:
    - python

test:
  imports:
    - pyclipper

about:
  home: https://github.com/fonttools/pyclipper
  license: MIT
  license_family: MIT
  license_file: 
    - LICENSE
    - LICENSE.txt
  summary: "Cython wrapper for the C++ translation of the Angus Johnson's Clipper library (ver. 6.4.2)"

  description: |
    "Pyclipper is a Cython wrapper exposing public functions and classes of the C++ 
     translation of the Angus Johnson’s Clipper library (ver. 6.4.2)."
  dev_url: https://github.com/fonttools/pyclipper

extra:
  recipe-maintainers:
    - jakakokosar
