{% set name = "pyclipper" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyclipper-{{ version }}.zip
  sha256: 48a1b5c585aea10e5b9c0b82d6abe2642fafd9ef158b9921852bc4af815ca20c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28
    - setuptools_scm >=1.11.1
  run:
    - python

test:
  imports:
    - pyclipper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/pyclipper
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.txt
  summary: Cython wrapper for the C++ translation of the Angus Johnson's Clipper library (ver. 6.4.2)

  description: |
    "Pyclipper is a Cython wrapper exposing public functions and classes of the C++ 
     translation of the Angus Johnson’s Clipper library (ver. 6.4.2)."
  dev_url: https://github.com/fonttools/pyclipper

extra:
  recipe-maintainers:
    - jakakokosar
