{% set name = "pyclipper" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyclipper-{{ version }}.zip
  sha256: ca3751e93559f0438969c46f17459d07f983281dac170c3479de56492e152855

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28
    - setuptools_scm >=1.11.1
  run:
    - python

test:
  imports:
    - pyclipper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/pyclipper
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.txt
  summary: Cython wrapper for the C++ translation of the Angus Johnson's Clipper library (ver. 6.4.2)

  description: |
    "Pyclipper is a Cython wrapper exposing public functions and classes of the C++ 
     translation of the Angus Johnson’s Clipper library (ver. 6.4.2)."
  dev_url: https://github.com/fonttools/pyclipper

extra:
  recipe-maintainers:
    - jakakokosar
